GET http://localhost:3000/posts
Content-Type: application/json

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "descricao": "Gato Post",
    "imgUrl": "https://placecats.com/millie/300/150",
    "alt": "Gato fazendo um post"
}

###

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="imagem"; filename="image.png"
Content-Type: image/png

< ./images/cat1.png
--MfnBoundry--

###

PUT  http://localhost:3000/upload/67410d898569c7e88078f0c8
Content-Type: application/json

{
    "alt": "Foto do gatinho"
}

###

GET http://localhost:3000/67410d898569c7e88078f0c8.png

###

POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="imagem"; filename="image.png"
Content-Type: image/png

< ./images/city1.png
--MfnBoundry--

###

PUT  http://localhost:3000/upload/67410ec98569c7e88078f0c9
Content-Type: application/json

{
    "alt": "Foto da cidade"
}

###

GET http://localhost:3000/67410ec98569c7e88078f0c9.png

###
